---

- name: "Check if spdlog installed"
  stat:
    path: /usr/local/include/spdlog
  register: sl_stat

- name: "Download the spdlog release"
  shell: "{{ item }}"
  args:
    chdir: "/tmp"
  with_items:
    - "wget https://github.com/gabime/spdlog/archive/v1.5.0.tar.gz"
    - "tar -xf v1.5.0.tar.gz"
    - "mkdir spdlog-1.5.0/build"
  when: sl_stat.stat.exists == False

- name: "Make and install"
  become: yes
  shell: "{{ item }}"
  args:
    chdir: "/tmp/spdlog-1.5.0/build"
  with_items:
    - "cmake .."
    - "make -j 3"
    - "make install"
  when: sl_stat.stat.exists == False

- name: "Clean up"
  become: yes
  file:
    state: absent
    path: "/tmp/spdlog-1.5.0"
